version: "3"

services:
  mac-movies-db:
    image: "postgres:latest"
    environment:
      - DATABASE_HOSE=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mac_minesweaper_db
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  server:
    container_name: mac_minesweaper_server
    image: mac_minesweaper_server
    build: ./server
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - db
  frontend:
    container_name: mac_minesweaper_frontend
    image: mac_minesweaper_frontend
    build: ./client
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - server
networks:
  my_network:
    driver: bridge
